server:
  port: 9000

logging:
  level:
    ROOT: INFO
    com.guavapay.dbs: DEBUG
    org.hibernate: DEBUG

spring:
  application:
    name: adapter-websocket
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
      password: